trigger:
- master

name: $(Build.BuildId)

variables:
- name: BuildConfiguration
  value: Release

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Generate NuGet Package
  inputs:
    command: 'pack'
    packagesToPack: 'src/**/*.csproj'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    testRunTitle: 'Code Gen Helpers'
    workingDirectory: 'tests'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'nuget'
    publishLocation: 'pipeline'

