trigger:
- master

name: $(Build.BuildId)

variables:
- name: BuildConfiguration
  value: Release

stages:
- stage: build
  displayName: Build
  jobs:
  - job: buildAndTest
    displayName: 'Build & Test'
    pool:
      vmImage: windows-latest
    steps:
    - task: UseDotNet@2
      inputs:
        useGlobalJson: true

    - task: NuGetToolInstaller@1
      inputs:
        checkLatest: true

    - task: NuGetCommand@2
      displayName: NuGet Restore
      inputs:
        command: restore

    - task: MSBuild@1
      displayName: Build & Pack
      inputs:
        configuration: $(BuildConfiguration)

    - task: DotNetCoreCLI@2
      displayName: Run Unit Tests
      inputs:
        command: 'test'
        nobuild: true
        projects: '**/*.csproj'
        testRunTitle: 'Code Gen Helpers'
        workingDirectory: 'tests'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'nuget'
        publishLocation: 'pipeline'

    - task: NuGetCommand@2
      displayName: NuGet Push
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'SponsorConnect'
